### ISSUE TITLE
App crashing in release mode as soon as button clicked to open camera

### ISSUE THREAD

**Issue by butt09** [Anyline/anyline-ocr-flutter-module#25]
Working fine in debug mode but in release mode when I click to open the camera, it asked for permission, when permission granted in crashes the app and show following error in console.

E/AndroidRuntime(15097): FATAL EXCEPTION: main
E/AndroidRuntime(15097): Process: com.example.mrzapp, PID: 15097
E/AndroidRuntime(15097): java.lang.RuntimeException: Unable to resume activity {com.example.mrzapp/io.anyline.flutter.Anyline4Activity}: java.lang.RuntimeException: Plugin was not initialized
E/AndroidRuntime(15097):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3919)
E/AndroidRuntime(15097):        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3951)
E/AndroidRuntime(15097):        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
E/AndroidRuntime(15097):        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime(15097):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime(15097):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
E/AndroidRuntime(15097):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15097):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(15097):        at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(15097):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15097):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(15097):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(15097): Caused by: java.lang.RuntimeException: Plugin was not initialized
E/AndroidRuntime(15097):        at io.anyline.view.ScanView.k0(Unknown Source:84)
E/AndroidRuntime(15097):        at io.anyline.flutter.Anyline4Activity.onResume(Unknown Source:5)
E/AndroidRuntime(15097):        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1514)
E/AndroidRuntime(15097):        at android.app.Activity.performResume(Activity.java:7305)
E/AndroidRuntime(15097):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3911)
E/AndroidRuntime(15097):        ... 11 more

**Comment by butt09** [comment]
why closed?? it didn't solve hy issue

**Comment by berndkamplanyline** [comment]
Thanks for raising your support request via the Anyline Helpdesk! Rest assured that we are working on it. Github Issues, on the other hand are being closed without being inspected and the below message usually guides posters to use our Helpdesk.

---
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!

**Comment by johansutrisno** [comment]
Hi, how to solve this issue?

**Comment by johansutrisno** [comment]
Okay, thank you very much.
