### ISSUE TITLE
[{value: 4303607, format: CODE_128}] barcode result flutter

### ISSUE THREAD

**Issue by arbahaam** [Anyline/anyline-ocr-flutter-module#4]
Hi when scanning is complete barcode result returns as  [{value: 4303607, format: CODE_1] in flutter. How can I solve this?

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
