### ISSUE TITLE
[iOS] Runtime fatal exception when start scanning -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

### ISSUE THREAD

**Issue by AndreiCosmaPnt** [Anyline/anyline-ocr-flutter-module#6]
Hello,

When performing startScanning the app crashes on iOS. On Android it works fine.

These are the logs:
Launching lib/main.dart on Cosma’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 6T5FFAQ2H8
Running Xcode build...
Xcode build done.                                           169.2s
Installing and launching...
(lldb) 2021-11-10 12:11:25.234628+0200 Runner[1777:272860] Errors found! Invalidating cache...
Writing analzed variants.
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Debug service listening on ws://127.0.0.1:52793/llkbPUM7X94=/ws
Syncing files to device Cosma’s iPhone...
Errors found! Invalidating cache...
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
AnylineSDK Version 24.1 (1563)
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x182dbc05c 0x19b2d6f54 0x182ec5538 0x182ed0680 0x182d7946c 0x182d97e1c 0x1008e990c 0x1008ce150 0x1008ccc00 0x1008cd0e8 0x10087756c 0x18537ad70 0x18537d824 0x185350438 0x1852256d0 0x18559922c 0x1856a2aa8 0x18548d958 0x185429da0 0x1855a05dc 0x1854b2d84 0x103b00664 0x100870c8c 0x10087be74 0x103fc57f8 0x103b11f00 0x103e1d5f0 0x103dc239c 0x103dc5994 0x182dd1278 0x182d55c50 0x182d5044c 0x182d2ec68 0x182d423c8 0x19e55338c 0x1856e8060 0x185465b8c 0x1002b56a0 0x1017bda24)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b980d9c4 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b980d9c4 <+8>:  b.lo   0x1b980d9e4               ; <+40>
    0x1b980d9c8 <+12>: pacibsp 
    0x1b980d9cc <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b980d9d0 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.

Thanks,
Andrei

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
