### ISSUE TITLE
Update permission handler

### ISSUE THREAD

**Issue by albo1337** [Anyline/anyline-ocr-flutter-module#7]
Is it possible that you update the permission handler to the newest version. I am not able to use this lib, because an other essential lib uses a higher version of permission_handler.

Thank you very much!

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
